[package]
name = "muzak"
version = "2.1.0"
edition = "2024"

[dependencies]
rodio = { git = "https://github.com/RustAudio/rodio", rev = "f2cac6eaaead1ee017f7eb82b4f0c6bc14039ae3", features = ["noise"] }
strum = { version = "0.27.0", features = ["derive"] }
winnow = "0.7.2"
musicxml = { git = "https://github.com/The0x539/musicxml", branch = "copy-clone" }

dialoguer = { version = "0.11.0", optional = true }
clap = { version = "4.5.29", optional = true, features = ["derive"] }
wavers = { version = "1.5.1", optional = true }
bytemuck = { version = "1.21.0", optional = true }

[features]
default = ["build-binary"]
build-binary = [ "dialoguer", "wavers", "clap", "bytemuck"]
bytemuck = ["dep:bytemuck"]

[lib]
name = "muzak"

[[bin]]
name = "muzak"
required-features = ["build-binary"]
